### ISSUE TITLE
Prática 1 - GitHub Issues - Instruções Gerais

### ISSUE THREAD

**Issue by ramidedantas** [ramidedantas/GCMS-2022-1#1]
**Bem-vindos ao repositório da disciplina.**

Sigam as instruções da prática com atenção. Para este passo, dê uma reação neste comentário e depois faça um novo comentário:
* Colocar *link* para um repositório seu (caso tenha);
* Caso não tenha, incluir link para o repositório que você explorou acima;
* Colocar imagem (*screenshot*) do seu perfil no GitHub;
* Colocar reações nos comentários dos colegas.

**Comment by rasd** [comment]
[Repositório](https://github.com/rasd/SeminarioGithub)
![Capture](https://user-images.githubusercontent.com/3944560/161317742-a0060c1f-668f-4a0e-b692-2a633109b777.PNG)

**Comment by scpaes** [comment]
New comment

**Comment by Ruukaas** [comment]
https://github.com/Ruukaas/Pokedex
![A](https://user-images.githubusercontent.com/60784320/161356520-ee12b6dc-ab32-4044-82da-c071676840a1.png)

**Comment by RaphaelAlcantara** [comment]
Link do repositorio - https://github.com/RaphaelAlcantara/GerenciaDeConfig

![printGit](https://user-images.githubusercontent.com/87040140/161356739-2b30c87f-3c9b-4127-a614-dd4849fa107f.png)

**Comment by gabrielgou** [comment]
[Repositório](https://github.com/gabrielgou/consultorio)
![image](https://user-images.githubusercontent.com/14056923/161356644-440991bc-8828-4c10-a12a-020382eaa125.png)

**Comment by davidsonfe** [comment]
![image](https://user-images.githubusercontent.com/61193894/161356854-0ea824ec-c99d-46a7-b4eb-368e5220ea13.png)

**Comment by lucasplucena** [comment]
https://github.com/lucasplucena/pg-Git

![image](https://user-images.githubusercontent.com/60987410/161356801-8543ea14-5ad9-43ee-a770-c55521c36642.png)

**Comment by IvanRibeiro011** [comment]
![Captura de tela 2022-04-01 214731](https://user-images.githubusercontent.com/75269330/161356947-ec20f3f4-dde1-490e-93a3-4d9e84b373e4.png)

**Comment by andresonalcf** [comment]
[Meu repositório](https://github.com/andresonalcf/IFPE)
![image](https://user-images.githubusercontent.com/78571296/161356945-5f9b5519-d102-4f65-8278-1f8cdbefc3ea.png)

**Comment by flaviovieira1** [comment]
https://github.com/microsoft/vscod
![Captura de Tela (1)](https://user-images.githubusercontent.com/102838062/161357006-f95d79e1-ce6d-4f73-a35a-a4e0eb488865.png)
e

**Comment by IzavanCorreia** [comment]
Repositório: https://github.com/IzavanCorreia/r-shiny-package
![Captura de tela de 2022-04-01 21-57-55](https://user-images.githubusercontent.com/54564167/161357037-e929e0ca-092a-4b5c-9f21-5e53e7f23a57.png)

**Comment by netosantosbr** [comment]
[Meu repositório](https://github.com/netosantosbr/taxa-metabolica-basal)

![image](https://user-images.githubusercontent.com/77360799/161357144-3f559bac-6ca5-4dc9-9159-2d524b4bf0a5.png)

**Comment by PeuSouza** [comment]
Link do Repositório https://github.com/PeuSouza/GSOFT
![Capturar](https://user-images.githubusercontent.com/78571318/161357226-ee9170e4-3fd0-4ea4-89cf-6ebcf70ed73e.PNG)

**Comment by vinny-vin** [comment]
[Repositório](https://github.com/vinny-vin)
![image](https://user-images.githubusercontent.com/54315909/161357309-91ca7729-e7fb-4c4e-8780-a121a852d7aa.png)

**Comment by IgrCabral** [comment]
repositório visitado : 
https://github.com/TextoTecidoTexto/TextoTecidoTabelas

![Captura de tela 2022-04-01 213547](https://user-images.githubusercontent.com/102838056/161357444-d0449131-3698-4750-895d-97d35a432d2d.png)

**Comment by BrunoHldr** [comment]
[https://github.com/BrunoHldr/teste_da_aula](url)

![Sem título](https://user-images.githubusercontent.com/78571307/161357463-3bb4d1d5-c232-408e-b199-ad4743236e58.png)

**Comment by Well-Programmer** [comment]
![meugithab](https://user-images.githubusercontent.com/102838244/161357600-21e8f42d-1008-4042-8ac0-d016679c0313.png)

**Comment by Well-Programmer** [comment]
[https://github.com/Wsanbey](url)

**Comment by joshuairwing** [comment]
[Repositório](https://github.com/joshuairwing/Carrinhogithub)
![perfil](https://user-images.githubusercontent.com/78566594/161363577-476314cc-e367-4f7c-a001-1ce7ed054c19.png)

**Comment by savate** [comment]
Repositório: [https://github.com/savate/CRUDBooks](url)
![image](https://user-images.githubusercontent.com/78154142/161457077-e57e838f-7af6-419f-8af8-6711bfe096b8.png)

**Comment by Lucas-Pavao** [comment]
https://github.com/Lucas-Pavao/CRUDLivro
![Captura de tela 2022-04-06 144503](https://user-images.githubusercontent.com/89342683/162038372-c809f4e9-041b-4076-a291-b0df31be7209.png)
s

**Comment by willjsan** [comment]
> 

https://github.com/willjsan/Android/tree/basics_3/Android_basics
![image](https://user-images.githubusercontent.com/49081567/162042371-69fd5e8a-94db-4f9e-89db-48986df1a134.png)

**Comment by LUCASRENAA** [comment]
https://github.com/LUCASRENAA
![github](https://user-images.githubusercontent.com/58091788/162053082-d74fb187-5ac4-4dc4-9000-22d4a1a7057d.png)

**Comment by owlmilo1** [comment]
https://github.com/owlmilo1/CRUD_Books

![image](https://user-images.githubusercontent.com/60450556/162110786-352d1608-5190-4477-b20e-6fb74dbea324.png)

**Comment by JorgeLucasIFPE** [comment]
[https://github.com/tensorflow/tensorflow](url)

![image](https://user-images.githubusercontent.com/103222129/162325718-c3dce1e6-6a7e-4e2b-bb8a-aba81ab28f32.png)

**Comment by WoederRamos** [comment]
![Captura de tela 2023-03-24 213022](https://user-images.githubusercontent.com/78571285/227667629-d876dc3b-f59e-4ae0-bf7d-533cd83a1917.png)

**Comment by ramidedantas** [comment]
@WoederRamos você modificou a issue do repositório de um semestre anterior.
