### ISSUE TITLE
Pedido de colaboração

### ISSUE THREAD

**Issue by JorgeLucasIFPE** [ramidedantas/GCMS-2022-1#27]
@ramidedantas

**Comment by ramidedantas** [comment]
Convite enviado, aguardando aceite.

**Comment by ramidedantas** [comment]
@JorgeLucasIFPE convite refeito, aguardando aceite.

**Comment by JorgeLucasIFPE** [comment]
@ramidedantas, Não está aparecendo nada para mim

**Comment by ramidedantas** [comment]
Convite aceito, fechando.
